### PR TITLE
add workaround for microsoft ssh clone requirements

### PR DESCRIPTION
**Pull request by condaatje**
Just a heads up that this doesn't clone properly without a github-registered ssh key. modified readme with a workaround.

### CODE REVIEW

**Comment by Spacefreak18** [comment]
thanks for your interest!

we can just change the .gitmodules file to use https, right?

if you've made any progress running this on Windows, i'd love the feedback!

**Comment by condaatje** [comment]
yea either way - whichever you prefer. I just added it to the readme so as not to mess up your default system




------- Original Message -------

**Comment by condaatje** [comment]
ok I removed the workaround from the readme and just put in https as default for the submodule

**Review by Spacefreak18 — APPROVED** [review]
Thanks so much!

**Pull request merged**
